In [8]:
import pandas as pd # pandas is a liberary

# it has two data structures 
# 1.dataframes  --> print  the data in a tabular format
# 2.Series  --> print the data in a sequence format 

data=[(10,20,30,40,50,60,70,80,90,100),(1,2,3,4,5,6,7,8,9,10),(11,12,13,14,15,16,17,18,19,20),(21,22,23,24,25,26,27,28,29,30)]
print(data)

[(10, 20, 30, 40, 50, 60, 70, 80, 90, 100), (1, 2, 3, 4, 5, 6, 7, 8, 9, 10), (11, 12, 13, 14, 15, 16, 17, 18, 19, 20), (21, 22, 23, 24, 25, 26, 27, 28, 29, 30)]

In [9]:
pd.DataFrame(data)

    0   1   2   3   4   5   6   7   8    9
0  10  20  30  40  50  60  70  80  90  100
1   1   2   3   4   5   6   7   8   9   10
2  11  12  13  14  15  16  17  18  19   20
3  21  22  23  24  25  26  27  28  29   30

In [10]:
pd.Series(data)

0    (10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
1              (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
2     (11, 12, 13, 14, 15, 16, 17, 18, 19, 20)
3     (21, 22, 23, 24, 25, 26, 27, 28, 29, 30)
dtype: object

In [14]:
# importing a csv fie in pandas 

df=pd.read_csv(r"D:\csv_file\nifty_500.csv")
df

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
0,3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
1,Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
2,Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
3,ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
4,Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
497,ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
498,Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
499,Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
500,Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [16]:
# the head method is used to filter the first five rows 
df.head()

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
0,3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
1,Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
2,Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
3,ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
4,Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84

In [17]:
# the tail method is used filter the last five rows 
df.tail()

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
496,Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.0,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
497,ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.0,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
498,Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.0,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
499,Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.0,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
500,Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.0,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [19]:
# this can be used to filter the nnumber of rows 
df.head(25)

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
0,3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
1,Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
2,Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
3,ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
4,Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
5,Aditya Birla Capital Ltd.,ABCAPITAL,Financial Services,EQ,89.00,90.60,88.35,89.40,90.25,0.85,0.95,2401323,2.151826e+08,139.20,85.60,-23.75,-11.57
6,Aditya Birla Fashion and Retail Ltd.,ABFRL,Consumer Services,EQ,235.60,243.50,235.60,237.05,242.20,5.15,2.17,1014277,2.435482e+08,322.00,189.35,9.87,-12.62
7,Aditya Birla Sun Life AMC Ltd.,ABSLAMC,Financial Services,EQ,400.05,406.70,400.00,400.05,405.90,5.85,1.46,34489,1.390183e+07,722.90,375.00,-,-5.09
8,ACC Ltd.,ACC,Construction Materials,EQ,2122.95,2174.00,2122.95,2121.95,2171.70,49.75,2.34,284645,6.136206e+08,2589.00,1900.00,5.32,-3.48
9,Adani Enterprises Ltd.,ADANIENT,Metals & Mining,EQ,2189.90,2242.00,2138.25,2190.90,2229.25,38.35,1.75,2141743,4.695579e+09,2420.95,1332.75,45.33,1.08
10,Adani Green Energy Ltd.,ADANIGREEN,Power,EQ,1928.00,1978.90,1902.00,1929.60,1963.25,33.65,1.74,1206875,2.344656e+09,3050.00,874.80,-,2.15
11,Adani Ports and Special Economic Zone Ltd.,ADANIPORTS,Services,EQ,670.00,680.00,656.00,672.05,678.30,6.25,0.93,3151179,2.105492e+09,924.65,651.95,-4.50,-9.16
12,Adani Transmission Ltd.,ADANITRANS,Power,EQ,2500.00,2583.70,2226.30,2473.65,2452.00,-21.65,-0.88,741152,1.847855e+09,3000.00,863.00,-,20.37
13,Advanced Enzyme Tech Ltd.,ADVENZYMES,Fast Moving Consumer Goods,EQ,266.20,268.70,258.40,266.20,264.00,-2.20,-0.83,40076,1.054961e+07,435.95,258.40,-35.78,-7.02
14,Aegis Logistics Ltd.,AEGISCHEM,Oil Gas & Consumable Fuels,EQ,208.70,212.60,205.15,209.00,211.45,2.45,1.17,247355,5.173182e+07,386.00,167.25,-39.22,-3.95
15,Affle (India) Ltd.,AFFLE,Information Technology,EQ,1060.00,1060.30,1004.65,1060.30,1010.00,-50.30,-4.74,241660,2.469838e+08,1511.00,763.02,-,0.78
16,AIA Engineering Ltd.,AIAENG,Capital Goods,EQ,2233.80,2242.45,2170.20,2223.80,2210.00,-13.80,-0.62,42620,9.424049e+07,2350.00,1475.05,3.91,-2.37
17,Ajanta Pharmaceuticals Ltd.,AJANTPHARM,Healthcare,EQ,1233.00,1275.05,1229.35,1235.60,1265.90,30.30,2.45,109740,1.372935e+08,2435.00,1186.00,-42.50,-27.87
18,Alkem Laboratories Ltd.,ALKEM,Healthcare,EQ,2995.00,3035.00,2970.95,2998.55,3011.25,12.70,0.42,21837,6.552476e+07,4070.00,2828.00,-6.28,-4.78
19,Alkyl Amines Chemicals Ltd.,ALKYLAMINE,Chemicals,EQ,2525.00,2609.90,2506.20,2517.65,2552.85,35.20,1.40,26377,6.724843e+07,4749.00,2506.20,-30.00,-7.77
20,Allcargo Logistics Ltd.,ALLCARGO,Services,EQ,259.00,271.50,256.00,262.95,269.00,6.05,2.30,502907,1.333911e+08,412.00,152.50,64.50,-17.76
21,Alok Industries Ltd.,ALOKINDS,Textiles,BE,22.30,22.30,21.50,22.00,21.55,-0.45,-2.05,1040692,2.264546e+07,35.80,18.85,-,-
22,Amara Raja Batteries Ltd.,AMARAJABAT,Automobile and Auto Components,EQ,459.10,471.70,456.05,458.70,469.50,10.80,2.35,438273,2.027276e+08,781.60,438.05,-38.43,-8.69
23,Amber Enterprises India Ltd.,AMBER,Consumer Durables,EQ,2251.00,2348.20,2251.00,2246.65,2325.00,78.35,3.49,85424,1.977446e+08,4025.95,2040.00,-23.22,-14.67
24,Ambuja Cements Ltd.,AMBUJACEM,Construction Materials,EQ,363.95,368.60,362.10,363.00,367.50,4.50,1.24,2763265,1.011079e+09,442.50,274.00,6.56,-1.73

In [20]:
df.tail(7) # last seven rows

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
494,Yes Bank Ltd.,YESBANK,Financial Services,EQ,12.65,12.75,12.55,12.65,12.7,0.05,0.40,18633694,2.359026e+08,16.25,10.50,-6.64,-3.80
495,Zee Entertainment Enterprises Ltd.,ZEEL,Media Entertainment & Publication,EQ,213.00,215.85,210.60,214.10,215.5,1.40,0.65,4131369,8.808079e+08,378.70,166.80,-0.30,-15.33
496,Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.0,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
497,ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.0,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
498,Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.0,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
499,Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.0,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
500,Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.0,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [25]:
# questions
#1. to filter the company names of "Financial Services" sector

df['Company Name'][df['Industry']=='Financial Services']

2                       Aavas Financiers Ltd.
5                   Aditya Birla Capital Ltd.
7              Aditya Birla Sun Life AMC Ltd.
25                             Angel One Ltd.
31     Aptus Value Housing Finance India Ltd.
                        ...
442          Tata Investment Corporation Ltd.
469                                  UCO Bank
472                       Union Bank of India
474         UTI Asset Management Company Ltd.
494                             Yes Bank Ltd.
Name: Company Name, Length: 88, dtype: object

In [27]:
# 2.how many companies 

leng = df['Company Name'][df['Industry']=='Financial Services']
print(len(leng))

88

In [32]:
# 3.shape of the csv file  (rows and coloums)
df.shape

(501, 17)

In [33]:
# to print the rows and coloums

rows,columns=df.shape

rows

501

In [34]:
columns

17

In [35]:
# 4.to scice the rows 

df[10:20] # from row 10 t0 19

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
10,Adani Green Energy Ltd.,ADANIGREEN,Power,EQ,1928.0,1978.90,1902.00,1929.60,1963.25,33.65,1.74,1206875,2.344656e+09,3050.00,874.80,-,2.15
11,Adani Ports and Special Economic Zone Ltd.,ADANIPORTS,Services,EQ,670.0,680.00,656.00,672.05,678.30,6.25,0.93,3151179,2.105492e+09,924.65,651.95,-4.50,-9.16
12,Adani Transmission Ltd.,ADANITRANS,Power,EQ,2500.0,2583.70,2226.30,2473.65,2452.00,-21.65,-0.88,741152,1.847855e+09,3000.00,863.00,-,20.37
13,Advanced Enzyme Tech Ltd.,ADVENZYMES,Fast Moving Consumer Goods,EQ,266.2,268.70,258.40,266.20,264.00,-2.20,-0.83,40076,1.054961e+07,435.95,258.40,-35.78,-7.02
14,Aegis Logistics Ltd.,AEGISCHEM,Oil Gas & Consumable Fuels,EQ,208.7,212.60,205.15,209.00,211.45,2.45,1.17,247355,5.173182e+07,386.00,167.25,-39.22,-3.95
15,Affle (India) Ltd.,AFFLE,Information Technology,EQ,1060.0,1060.30,1004.65,1060.30,1010.00,-50.30,-4.74,241660,2.469838e+08,1511.00,763.02,-,0.78
16,AIA Engineering Ltd.,AIAENG,Capital Goods,EQ,2233.8,2242.45,2170.20,2223.80,2210.00,-13.80,-0.62,42620,9.424049e+07,2350.00,1475.05,3.91,-2.37
17,Ajanta Pharmaceuticals Ltd.,AJANTPHARM,Healthcare,EQ,1233.0,1275.05,1229.35,1235.60,1265.90,30.30,2.45,109740,1.372935e+08,2435.00,1186.00,-42.50,-27.87
18,Alkem Laboratories Ltd.,ALKEM,Healthcare,EQ,2995.0,3035.00,2970.95,2998.55,3011.25,12.70,0.42,21837,6.552476e+07,4070.00,2828.00,-6.28,-4.78
19,Alkyl Amines Chemicals Ltd.,ALKYLAMINE,Chemicals,EQ,2525.0,2609.90,2506.20,2517.65,2552.85,35.20,1.40,26377,6.724843e+07,4749.00,2506.20,-30.00,-7.77

In [36]:
df[:] # to print all the rows

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
0,3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
1,Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
2,Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
3,ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
4,Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
497,ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
498,Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
499,Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
500,Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [41]:
# to print the name of the columns 

df.columns

Index(['Company Name', 'Symbol', 'Industry', 'Series', 'Open', 'High', 'Low',
       'Previous Close', 'Last Traded Price', 'Change', 'Percentage Change',
       'Share Volume', 'Value (Indian Rupee)', '52 Week High', '52 Week Low',
       '365 Day Percentage Change', '30 Day Percentage Change'],
      dtype='object')

In [46]:
# to print the name of the rows

df['Company Name']

0                                         3M India Ltd.
1                                      Aarti Drugs Ltd.
2                                 Aavas Financiers Ltd.
3                                        ABB India Ltd.
4                                     Abbott India Ltd.
                             ...
496                             Zensar Technolgies Ltd.
497    ZF Commercial Vehicle Control Systems India Ltd.
498                                         Zomato Ltd.
499                             Zydus Lifesciences Ltd.
500                                 Zydus Wellness Ltd.
Name: Company Name, Length: 501, dtype: object

In [48]:
# to find the type 

type(df['Symbol'])
type(df['Share Volume'])
type(df['Change'])

pandas.core.series.Series

In [49]:
# to print only two or three  coloums

df[['Company Name','Industry','Share Volume']]

,Company Name,Industry,Share Volume
0,3M India Ltd.,Diversified,4159
1,Aarti Drugs Ltd.,Healthcare,31782
2,Aavas Financiers Ltd.,Financial Services,150704
3,ABB India Ltd.,Capital Goods,97053
4,Abbott India Ltd.,Healthcare,12396
...,...,...,...
496,Zensar Technolgies Ltd.,Information Technology,186578
497,ZF Commercial Vehicle Control Systems India Ltd.,Automobile and Auto Components,12790
498,Zomato Ltd.,Consumer Services,112078641
499,Zydus Lifesciences Ltd.,Healthcare,862373
500,Zydus Wellness Ltd.,Fast Moving Consumer Goods,10803

In [55]:
# some operations with data 
df['Share Volume'].max()

125788305

In [57]:
df['Share Volume'].min()

1507

In [59]:
# this is used to describe the data and statistical concepts like  mean , 25 percentile etc 

df.describe()

,Open,High,Low,Previous Close,Last Traded Price,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low
count,501.000000,501.000000,501.000000,501.000000,501.000000,5.010000e+02,5.010000e+02,501.000000,501.000000
mean,1525.904491,1553.804990,1504.042415,1528.061277,1536.925449,2.580350e+06,8.635146e+08,2182.632196,1281.628982
std,4466.627117,4576.377692,4435.492332,4477.209376,4532.004734,9.407021e+06,4.335973e+09,5728.930152,3850.529646
min,6.750000,6.950000,6.700000,6.850000,6.800000,1.507000e+03,2.587223e+06,13.100000,4.550000
25%,215.300000,221.550000,210.600000,217.200000,214.650000,7.740500e+04,4.502265e+07,328.700000,166.800000
50%,551.100000,569.100000,547.000000,554.750000,563.000000,3.296100e+05,1.533133e+08,818.000000,438.050000
75%,1404.500000,1421.250000,1396.850000,1411.700000,1410.000000,1.235612e+06,6.644570e+08,2096.750000,1128.800000
max,70300.000000,72500.000000,70300.000000,70800.900000,71900.000000,1.257883e+08,9.211987e+10,87550.000000,63000.000000

In [88]:
# to print the company name whose share volume is high

# df[df['Company Name']]  [[df.'Share Volume'].max()]

df['Share Volume'].max()

125788305

In [93]:
df[df['Company Name']== df['Share Volume'].max()]

Empty DataFrame
Columns: [Company Name, Symbol, Industry, Series, Open, High, Low, Previous Close, Last Traded Price, Change, Percentage Change, Share Volume, Value (Indian Rupee), 52 Week High, 52 Week Low, 365 Day Percentage Change, 30 Day Percentage Change]
Index: []

In [75]:
# de get the index 

df.index

RangeIndex(start=0, stop=501, step=1)

In [76]:
df

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
0,3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
1,Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
2,Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
3,ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
4,Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
497,ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
498,Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
499,Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
500,Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [77]:
# now the index will be changes to Company Name
df.set_index('Company Name')

,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
Company Name,,,,,,,,,,,,,,,,
3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [78]:
df

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
0,3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
1,Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
2,Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
3,ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
4,Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
497,ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
498,Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
499,Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
500,Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [80]:
df.set_index('Company Name',inplace=True)

In [81]:
df # now the rows has been changed

,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
Company Name,,,,,,,,,,,,,,,,
3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [82]:
df.loc['Zomato Ltd.']

Symbol                                  ZOMATO
Industry                     Consumer Services
Series                                      EQ
Open                                     54.15
High                                      56.7
Low                                      52.55
Previous Close                           53.85
Last Traded Price                         56.0
Change                                    2.15
Percentage Change                         3.99
Share Volume                         112078641
Value (Indian Rupee)             6193465701.66
52 Week High                             169.0
52 Week Low                              50.05
365 Day Percentage Change                    -
30 Day Percentage Change                -27.86
Name: Zomato Ltd., dtype: object

In [84]:
# to change the index to normal 

df.reset_index(inplace=True)

In [85]:
df

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
0,3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
1,Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
2,Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
3,ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
4,Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
497,ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
498,Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
499,Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
500,Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25